

import React from 'react';
import {
  MessageSquare, Calculator, Speech, History, Globe, Atom, Beaker, Leaf, BookOpen, School, DollarSign, Laptop, Palette, Music, Volleyball, Scale, Book, BookMarked, Briefcase, Award, GraduationCap, Building, LifeBuoy
} from 'lucide-react';

export const allSubjects: string[] = [
  "nederlands", "wiskunde", "engels", "geschiedenis", "aardrijkskunde",
  "natuurkunde", "scheikunde", "biologie", "frans", "duits", "latijn", "economie",
  "informatica", "kunst", "muziek", "lichamelijke_opvoeding",
  "maatschappijleer", "ckv", "algemeen"
];

export const subjectIconMap: { [key: string]: React.ElementType } = {
  "nederlands": MessageSquare,
  "wiskunde": Calculator,
  "engels": Speech,
  "geschiedenis": History,
  "aardrijkskunde": Globe,
  "natuurkunde": Atom,
  "scheikunde": Beaker,
  "biologie": Leaf,
  "frans": BookOpen,
  "duits": School,
  "latijn": BookMarked,
  "economie": DollarSign,
  "informatica": Laptop,
  "kunst": Palette,
  "muziek": Music,
  "lichamelijke_opvoeding": Volleyball,
  "maatschappijleer": Scale,
  "ckv": Palette, // CKV is culturele en KUNSTzinnige vorming
  "algemeen": Book,
  "basisschool": GraduationCap,
  "basis": School,
  "mavo": School,
  "havo": School,
  "vwo": School,
  "mbo": Briefcase,
  "hbo": Building,
  "wo": GraduationCap,
  "anders": Book,
  "default": Book,
  "feedback_support": LifeBuoy,
};

export const subjectDisplayTranslations: { [key: string]: { [key: string]: string } } = {
  nl: {
    "nederlands": "Nederlands", "wiskunde": "Wiskunde", "engels": "Engels", "geschiedenis": "Geschiedenis", "aardrijkskunde": "Aardrijkskunde",
    "natuurkunde": "Natuurkunde", "scheikunde": "Scheikunde", "biologie": "Biologie", "frans": "Frans", "duits": "Duits", "latijn": "Latijn", "economie": "Economie",
    "informatica": "Informatica", "kunst": "Kunst", "muziek": "Muziek", "lichamelijke_opvoeding": "Lichamelijke Opvoeding",
    "maatschappijleer": "Maatschappijleer", "ckv": "CKV", "algemeen": "Algemeen",
    "basisschool": "Basisschool",
    "basis": "Basis",
    "mavo": "MAVO",
    "havo": "HAVO",
    "vwo": "VWO",
    "anders": "Anders",
  },
  en: {
    "nederlands": "Dutch", "wiskunde": "Mathematics", "engels": "English", "geschiedenis": "History", "aardrijkskunde": "Geography",
    "natuurkunde": "Physics", "scheikunde": "Chemistry", "biologie": "Biology", "frans": "French", "duits": "German", "latijn": "Latin", "economie": "Economics",
    "informatica": "Computer Science", "kunst": "Art", "muziek": "Music", "lichamelijke_opvoeding": "Physical Education",
    "maatschappijleer": "Social Studies", "ckv": "Cultural and Artistic Education", "algemeen": "General",
    "basisschool": "Primary School",
    "basis": "Basic",
    "mavo": "MAVO",
    "havo": "HAVO",
    "vwo": "VWO (Pre-University)",
    "anders": "Other",
  }
};

export const educationLevels: string[] = ["basisschool", "basis", "mavo", "havo", "vwo", "anders"];

export const defaultProfileImage: string = "https://picsum.photos/100/100";

export const availableThemeColors: string[] = ['emerald', 'blue', 'rose', 'purple', 'pink', 'indigo', 'teal', 'amber'];

export const availableFonts: { id: string, name: string, className: string }[] = [
    { id: 'inter', name: 'Inter', className: 'font-inter' },
    { id: 'poppins', name: 'Poppins', className: 'font-poppins' },
    { id: 'lato', name: 'Lato', className: 'font-lato' },
    { id: 'roboto-slab', name: 'Roboto Slab', className: 'font-roboto-slab' },
    { id: 'lora', name: 'Lora', className: 'font-lora' },
];

export const defaultHomeLayout: string[] = ['subjects', 'agenda', 'files'];

export const translations: { [key:string]: { [key: string]: string } } = {
  nl: {
    // Auth & General
    welcome_message: "Welkom, {name}!",
    welcome_title: "Welkom bij Schoolmaps!",
    welcome_description: "Al je schoolzaken op één plek. Organiseer je bestanden, beheer je agenda en versnel je leerproces.",
    create_account_login_button: "Account Aanmaken / Inloggen",
    register_title: "Registreer een Account",
    login_title: "Inloggen",
    your_name: "Volledige naam",
    email_address: "E-mailadres",
    password: "Wachtwoord",
    placeholder_name: "bv. Jan Jansen",
    placeholder_email: "jouw@email.com",
    placeholder_password: "********",
    school_name: "Naam van je school",
    class_name: "Klas (bv. H4B)",
    education_level: "Onderwijsniveau",
    register_account: "Registreer Account",
    login_button: "Login",
    already_account: "Al een account? Login hier",
    no_account_register: "Nog geen account? Registreer hier",
    success_registration: "Registratie succesvol! Controleer je e-mail om je account te verifiëren.",
    success_login: "Succesvol ingelogd! Welkom terug.",
    success_logout: "Je bent uitgelogd. Tot de volgende keer!",
    confirm_logout: "Weet je zeker dat je wilt uitloggen?",
    forgot_password: "Wachtwoord vergeten?",
    password_reset_sent: "Een e-mail voor wachtwoordherstel is verzonden naar {email}. Je gegevens blijven veilig bewaard.",
    guest_fallback_name: "Gebruiker",
    default: "Standaard",

    // Email Verification
    verify_email_title: "Verifieer je e-mailadres",
    verify_email_instructions: "We hebben een verificatielink gestuurd naar {email}. Klik op de link om je account te activeren.",
    verify_email_spam_check: "Niks ontvangen? Controleer je spamfolder of vraag hieronder een nieuwe e-mail aan.",
    verify_email_continue_button: "Ik heb geverifieerd, ga verder",
    verify_email_resend_button: "Stuur opnieuw",
    sending: "Versturen...",
    email_sent: "E-mail verzonden!",
    skip_verification_button: "Sla verificatie over (Test)",
    skip_verification_tooltip_title: "Tijdelijke testknop",
    skip_verification_tooltip_text: "De e-mail verificatie wordt momenteel herzien. Gebruik deze knop om tijdelijk door te gaan zonder verificatie. Deze optie wordt binnenkort verwijderd.",
    
    // Errors
    error_fill_all_fields: "Vul alstublieft alle verplichte velden in.",
    error_fill_current_step: "Vul alstublieft alle velden in deze stap in.",
    error_select_subjects_register: "Selecteer ten minste één vak om door te gaan.",
    error_unknown: "Er is een onbekende fout opgetreden. Probeer het opnieuw.",
    error_invalid_email: "Dit is geen geldig e-mailadres. Controleer het en probeer opnieuw.",
    error_invalid_credentials: "De combinatie van e-mail en wachtwoord is onjuist.",
    error_email_in_use: "Dit e-mailadres is al in gebruik. Probeer in te loggen.",
    error_weak_password: "Je wachtwoord is te zwak. Gebruik minimaal 6 tekens.",
    error_enter_email_for_reset: "Voer je e-mailadres in om je wachtwoord te resetten.",
    error_save_settings_failed: "Opslaan van instellingen mislukt. Probeer het opnieuw.",
    error_profile_pic_upload_failed: "Uploaden van profielfoto mislukt. Probeer het opnieuw.",
    error_password_reset_failed: "Verzenden van wachtwoordherstel mislukt.",
    error_guest_action_not_allowed: "Gastgebruikers kunnen deze actie niet uitvoeren.",
    error_profile_load_failed: "Kon je profiel niet laden. Controleer je verbinding of probeer het later opnieuw.",
    error_failed_to_load_tasks: "Kon taken niet laden. Controleer je verbinding.",
    error_failed_to_load_sets: "Kon studiereeksen niet laden. Controleer je verbinding.",
    error_failed_to_load_cards: "Kon kaarten niet laden. Controleer je verbinding.",
    error_account_disabled: "Je account is gedeactiveerd door een beheerder.",
    error_reauth_failed: "Verkeerd wachtwoord. Probeer het opnieuw.",
    error_account_deletion_failed: "Account verwijderen mislukt. Probeer het later opnieuw.",
    error_account_cleanup_failed: "Opschonen van account mislukt. Probeer het later opnieuw.",
    error_admin_login_failed: "Admin login mislukt. Kon instellingen niet laden.",
    error_failed_to_save_admin_settings: "Opslaan van admin-instellingen mislukt.",
    error_select_file_to_upload: "Selecteer een bestand om te uploaden.",
    error_add_file_failed: "Bestand toevoegen mislukt: {message}",
    error_delete_file_failed: "Bestanden verwijderen mislukt: {message}",
    error_invalid_date_time: "Ongeldige datum of tijd.",
    error_save_event_failed: "Afspraak opslaan mislukt: {message}",
    error_delete_event_failed: "Afspraak verwijderen mislukt: {message}",
    error_fetch_notes_failed: "Notities ophalen mislukt.",
    error_save_note_failed: "Notitie opslaan mislukt: {message}",
    error_delete_note_failed: "Notitie verwijderen mislukt.",
    error_flashcard_set_min_cards: "Je hebt minimaal 2 kaarten nodig voor de Meerkeuze modus.",
    error_general_srs_reset: "Voortgang resetten mislukt.",
    

    // Account Deletion
    delete_account_section_title: "Account Verwijderen",
    delete_account_section_description: "Deze actie is onomkeerbaar. Al je gegevens, inclusief bestanden, notities en agenda-items, worden permanent verwijderd.",
    delete_account_button: "Verwijder Mijn Account",
    reauth_modal_title: "Bevestig je identiteit",
    reauth_modal_description: "Voer je wachtwoord in om door te gaan. Dit is een veiligheidsmaatregel.",
    confirm_delete_account_button: "Ja, Verwijder Mijn Account Permanent",
    deleting_account_progress: "Account wordt verwijderd... Dit kan even duren.",
    success_account_deleted: "Je account is succesvol verwijderd. We vinden het jammer je te zien gaan.",

    // Account Cleanup
    cleanup_account_section_title: "Account Opschonen",
    cleanup_account_section_description: "Deze actie verwijdert al je content (bestanden, notities, agenda, etc.) maar behoudt je account en instellingen. Dit kan niet ongedaan worden gemaakt.",
    cleanup_account_button: "Schoon Mijn Account Op",
    reauth_modal_title_cleanup: "Account Opschonen Bevestigen",
    reauth_modal_description_cleanup: "Voer je wachtwoord in om het opschonen van je account te bevestigen. Al je content wordt permanent verwijderd.",
    confirm_cleanup_account_button: "Ja, Schoon Mijn Account Op",
    cleanup_account_progress: "Account wordt opgeschoond...",
    success_account_cleaned: "Je account is succesvol opgeschoond.",

    // Navigation
    my_subjects: "Mijn Vakken",
    calendar: "Agenda",
    extra_tools: "Extra Tools",
    flashcards: "Flashcards",
    study_timer: "Studeertimer",
    notes: "Notities",
    todo_list: "Takenlijst",
    settings: "Instellingen",
    app_info: "App Info",
    faq: "Veelgestelde Vragen",
    logout_button: "Uitloggen",
    feedback_support: "Feedback & Support",
    
    // Home & Subjects
    my_subjects_files: "Jouw School Bestanden",
    profile_incomplete_message: "Je profiel is nog niet compleet!",
    go_to_settings_message: "Ga naar Instellingen om je vakken te selecteren.",
    select_subjects: "Selecteer je vakken",
    add_custom_subject: "Voeg een eigen vak toe",
    custom_subject_placeholder: "Naam van het vak...",
    add_subject_button: "Toevoegen",
    error_subject_exists: "Dit vak bestaat al.",
    error_subject_empty: "Vaknaam mag niet leeg zijn.",
    no_files_found: "Geen bestanden gevonden in dit vak.",
    add_file_section_title: "Bestand toevoegen:",
    file_title_placeholder: "Titel (verplicht)",
    file_description_placeholder: "Beschrijving (optioneel)",
    add_file_button: "Voeg Bestand Toe",
    select_files_button: "Selecteer Bestanden",
    delete_selected_button: "Verwijder Geselecteerde",
    share_button: "Deel",
    back_to_subjects: "Terug naar Vakken",
    back_button: "Terug",
    error_enter_file_title: "Voer een titel in voor het bestand.",
    success_file_added: "Bestand succesvol toegevoegd!",
    error_select_files_delete: "Selecteer eerst bestanden om te verwijderen.",
    confirm_delete_files: "Weet je zeker dat je {count} bestand(en) wilt verwijderen?",
    success_files_deleted: "Geselecteerde bestanden succesvol verwijderd!",
    share_link_copied: "Deellink voor '{title}' gekopieerd!",
    error_copy_share_link: "Fout bij kopiëren deellink.",
    added_on: "Toegevoegd op",
    your_files_in: "Jouw bestanden in",
    your_subjects: "Jouw Vakken",
    recent_files_title: "Recente Bestanden",
    no_recent_files: "Je hebt nog geen bestanden toegevoegd.",
    todays_agenda_title: "Agenda voor Vandaag",
    no_events_today: "Geen afspraken voor vandaag. Geniet van je dag!",
    go_to_calendar: "Bekijk volledige agenda",

    // Settings
    settings_title: "Instellingen",
    profile_section: "Profiel",
    profile_picture_upload_label: "Profielfoto uploaden:",
    profile_picture_current: "Huidige profielfoto:",
    profile_picture_upload_success: "Profielfoto succesvol bijgewerkt!",
    upload_profile_picture_button: "Upload Profielfoto",
    save_profile_info_button: "Profiel Opslaan",
    success_settings_saved: "Instellingen succesvol opgeslagen!",
    choose_theme: "Kies je thema",
    font_preference: "Kies je lettertype",
    language_preference: "Taalvoorkeur",
    dutch: "Nederlands",
    english: "Engels",
    password_reset_section_title: "Wachtwoord Resetten",
    password_reset_section_description: "Klik op de knop om een wachtwoordherstele-mail te ontvangen op {email}.",
    send_reset_email_button: "Verstuur Herstel E-mail",
    settings_account_section: "Account",
    settings_appearance_section: "Weergave",
    settings_help_info_section: "Hulp & Info",
    settings_privacy_section: "Privacy",
    privacy_policy_content: "Uw privacy is belangrijk voor ons. Deze app verzamelt minimale persoonlijke gegevens om de functionaliteit te bieden. Bestanden die u uploadt, worden in uw privéopslag opgeslagen en zijn alleen voor u toegankelijk, tenzij u ze expliciet deelt.",
    version: "Versie",
    copyright: "Alle rechten voorbehouden.",
    saving: "Opslaan...",
    confirm_remove_subjects_warning: "Weet je zeker dat je deze vakken wilt deselecteren? De bijbehorende gegevens (bestanden, notities, etc.) worden niet verwijderd, maar zijn pas weer zichtbaar als je de vakken opnieuw selecteert.",
    app_offline_message: "U bent offline. Wijzigingen worden gesynchroniseerd wanneer u weer online bent.",
    app_back_online_message: "Welkom terug online! Uw gegevens worden gesynchroniseerd.",
    home_layout_title: "Startpagina Indeling Aanpassen",
    home_layout_description: "Sleep de widgets om de volgorde op je startpagina aan te passen.",
    widget_subjects: "Mijn Vakken",
    widget_agenda: "Agenda van Vandaag",
    widget_files: "Recente Bestanden",
    notifications_settings_title: "Meldingsinstellingen",
    enable_notifications: "Meldingen inschakelen",

    // Calendar
    calendar_title: "Jouw Agenda",
    add_event: "Nieuwe Afspraak",
    event_title: "Titel afspraak",
    event_description: "Beschrijving (optioneel)",
    event_type: "Type",
    event_subject: "Vak",
    select_date: "Datum",
    select_start_time: "Starttijd",
    select_end_time: "Eindtijd",
    add_event_button: "Voeg afspraak toe",
    no_events_day: "Geen afspraken voor deze dag.",
    edit_event: "Bewerken",
    delete_event_confirm: "Weet je zeker dat je '{title}' wilt verwijderen?",
    event_test: "Toets",
    event_presentation: "Presentatie",
    event_homework: "Huiswerk",
    event_oral: "Mondeling",
    event_other: "Overig",
    all_day: "Hele dag",
    today: "Vandaag",
    week_of: "Week van",
    previous_week: "Vorige",
    next_week: "Volgende",
    error_enter_event_title: "Voer een titel in voor de afspraak.",
    success_event_added: "Afspraak succesvol toegevoegd!",
    success_event_updated: "Afspraak succesvol bijgewerkt!",
    success_event_deleted: "Afspraak succesvol verwijderd!",
    all_subjects_option: "Alle Vakken",
    select_subject: "Selecteer Vak",

    // Tools
    notes_title: "Notities",
    add_note_title_placeholder: "Titel notitie (verplicht)",
    add_note_content_placeholder: "Begin met typen...",
    add_note_button: "Nieuwe Notitie",
    save_note_button: "Opslaan",
    confirm_delete_note: "Weet je zeker dat je deze notitie wilt verwijderen?",
    note_added_success: "Notitie succesvol toegevoegd!",
    note_updated_success: "Notitie succesvol bijgewerkt!",
    note_deleted_success: "Notitie succesvol verwijderd!",
    error_empty_note_title: "Titel van notitie mag niet leeg zijn.",
    
    todo_list_title: "Jouw Takenlijst",
    add_task_placeholder: "Voeg een nieuwe taak toe...",
    add_task_button: "Taak Toevoegen",
    no_tasks_found: "Geen taken gevonden. Voeg er een toe!",
    task_added_success: "Taak succesvol toegevoegd!",
    task_deleted_success: "Taak succesvol verwijderd!",
    task_updated_success: "Taak succesvol bijgewerkt!",
    confirm_delete_task: "Weet je zeker dat je deze taak wilt verwijderen?",
    error_empty_task: "Taak mag niet leeg zijn.",

    flashcards_title: "Jouw Flashcards",
    add_flashcard: "Flashcard Toevoegen",
    question: "Vraag",
    answer: "Antwoord",
    add_card_button: "Kaart Toevoegen",
    next_card: "Volgende",
    prev_card: "Vorige",
    flip_card: "Omdraaien",
    no_flashcards_found: "Geen flashcards gevonden voor deze set.",
    all_cards_learned_title: "Goed bezig!",
    all_cards_learned_desc: "Je hebt alle kaarten voor nu geleerd. Reset de voortgang om opnieuw te beginnen of kies een andere methode.",
    reset_and_start_over_button: "Reset & Leer Opnieuw",
    choose_other_method_button: "Kies Andere Methode",
    confirm_delete_flashcard: "Weet je zeker dat je deze flashcard wilt verwijderen?",
    flashcard_added_success: "Flashcards succesvol toegevoegd!",
    flashcard_deleted_success: "Flashcard succesvol verwijderd!",
    error_empty_flashcard: "Vraag en antwoord mogen niet leeg zijn.",
    
    // New Flashcard Deck translations
    select_a_subject_first: "Selecteer een vak om te beginnen",
    sets_for_subject: "Studiereeksen voor {subject}",
    select_set: "Selecteer een Studiereeks",
    create_new_set: "Nieuwe Studiereeks Maken",
    set_name_placeholder: "Naam van je set (bv. Hoofdstuk 1)",
    create_set_button: "Maak Set",
    no_sets_found: "Geen studiereeksen gevonden voor dit vak.",
    confirm_delete_set: "Weet je zeker dat je de set '{name}' en alle kaarten erin wilt verwijderen?",
    set_added_success: "Set succesvol aangemaakt!",
    set_deleted_success: "Set succesvol verwijderd!",
    error_empty_set_name: "Naam van de set mag niet leeg zijn.",
    back_to_sets: "Terug naar Sets",
    back_to_subjects_selection: "Terug naar vakken",
    manage_cards: "Beheer Kaarten",
    cards_in_set: "{count} kaarten",
    add_more_rows: "Voeg 5 extra rijen toe",

    // Flashcard Study Modes & Summary
    choose_study_mode: "Kies een studiemethode",
    study_mode_learn_title: "Leren",
    study_mode_learn_desc: "Slim algoritme (SRS) om woorden in je lange-termijngeheugen te krijgen. Ideaal om écht te leren.",
    study_mode_cram_title: "Stampen",
    study_mode_cram_desc: "Ga snel door alle kaarten heen. Perfect voor een snelle herhaling vlak voor een toets.",
    study_mode_mc_title: "Meerkeuze",
    study_mode_mc_desc: "Test je kennis met automatisch gegenereerde meerkeuzevragen. Daag jezelf uit!",
    start_session: "Start Sessie",
    show_answer: "Toon Antwoord",
    feedback_again: "Opnieuw",
    feedback_good: "Goed",
    reset_srs_progress: "Leer-voortgang resetten",
    reset_srs_confirm: "Weet je zeker dat je de leervoortgang voor deze set wilt resetten? Alle kaarten worden behandeld als nieuw.",
    session_complete: "Sessie Voltooid!",
    your_score: "Jouw score: {correct} / {total}",
    well_done_message: "Goed gedaan! Blijf zo doorgaan.",
    study_again_button: "Nog een keer",
    cards_to_go: "{count} kaarten te gaan",
    loading_cards: "Kaarten laden...",
    
    study_timer_title: "Studeertimer",
    focus_session: "Focus",
    break_session: "Pauze",
    focus_session_complete: "Focus sessie voltooid! Tijd voor pauze.",
    break_session_complete: "Pauze voorbij! Tijd om weer te focussen.",
    focusing_on: "Focussen op:",
    loading_tasks: "Taken laden...",
    no_specific_task: "-- Geen specifieke taak --",
    
    // UI
    confirm_button: "Bevestigen",
    cancel_button: "Annuleren",
    close_button: "Sluiten",
    select_level: "Selecteer Niveau",
    view_button: "Bekijk",
    delete: "Verwijder",
    copy_link: "Kopieer Link",
    next_button: "Volgende",
    uploading: "Uploaden...",

    // Intro Tutorial
    intro_step1_title: "Alles op één Plek",
    intro_step1_text: "Houd al je bestanden, notities en samenvattingen georganiseerd per vak. Nooit meer zoeken naar dat ene verslag.",
    intro_step2_title: "Beheer je Tijd",
    intro_step2_text: "Mis nooit meer een deadline met een overzichtelijke agenda voor al je toetsen, huiswerk en afspraken.",
    intro_step3_title: "Studeer Slimmer",
    intro_step3_text: "Gebruik onze slimme tools zoals flashcards en de studietimer om efficiënter te leren en betere cijfers te halen.",
    intro_step4_title: "Maak het Jouw Plek",
    intro_step4_text: "Kies je eigen kleuren en lettertype om de app perfect bij jouw stijl te laten passen. Jouw school, jouw look.",
    intro_step5_title: "Klaar om te Beginnen?",
    intro_step5_text: "Transformeer je schoolleven. Maak een account aan of log in om direct aan de slag te gaan.",
    intro_finish_button: "Aan de slag!",

    // Notifications & Streak
    notifications: "Notificaties",
    notifications_title: "Notificaties",
    no_notifications: "Je hebt nog geen notificaties.",
    no_notifications_disabled_title: "Meldingen zijn uitgeschakeld",
    no_notifications_disabled_text: "Je kunt ze inschakelen in Instellingen.",
    mark_all_as_read: "Markeer alles als gelezen",
    clear_all_notifications: "Wis alle notificaties",
    confirm_clear_all_notifications: "Weet je zeker dat je alle notificaties wilt verwijderen? Dit kan niet ongedaan worden gemaakt.",
    notifications_cleared: "Alle notificaties zijn gewist.",
    streak_notification: "Goed bezig! Je hebt een reeks van {count} dagen bereikt. Hou vol!",
    streak_lost_notification_title: "Reeks verbroken",
    streak_lost_notification_text: "Oh nee! Je reeks van {count} dagen is verbroken. Begin vandaag een nieuwe!",
    streak_days: "{count} dagen",
    
    // Admin
    admin_dashboard: "Admin Dashboard",
    users: "Gebruikers",
    broadcasts: "Mededelingen",
    send_broadcast: "Verstuur Mededeling",
    broadcast_title_placeholder: "Titel van je mededeling",
    broadcast_message_placeholder: "Typ je mededeling hier...",
    send_message_button: "Verstuur Bericht",
    broadcast_success: "Mededeling succesvol verstuurd!",
    error_broadcast_failed: "Versturen van mededeling mislukt.",
    error_broadcast_empty: "Titel en bericht van mededeling mogen niet leeg zijn.",
    error_deletion_failed: "Verwijderen mislukt.",
    past_broadcasts: "Verzonden Mededelingen",
    no_past_broadcasts: "Er zijn nog geen mededelingen verstuurd.",
    delete_all_broadcasts: "Verwijder Alle Mededelingen",
    confirm_delete_all_broadcasts: "Weet je zeker dat je alle mededelingen wilt verwijderen? Dit kan niet ongedaan worden gemaakt.",
    confirm_delete_all_broadcasts_and_notifications: "Weet je zeker dat je alle mededelingen en bijbehorende notificaties van alle gebruikers wilt verwijderen? Dit kan niet ongedaan worden gemaakt.",
    all_broadcasts_deleted: "Alle mededelingen en notificaties zijn verwijderd.",
    refresh_data: "Ververs Gegevens",
    actions: "Acties",
    status: "Status",
    active: "Actief",
    disabled: "Gedeactiveerd",
    last_login: "Laatst Ingelogd",
    enable_user: "Activeer",
    disable_user: "Deactiveer",
    confirm_disable_user: "Weet je zeker dat je gebruiker {name} wilt deactiveren? Ze kunnen niet meer inloggen.",
    confirm_enable_user: "Weet je zeker dat je gebruiker {name} wilt activeren? Ze kunnen weer inloggen.",
    user_status_updated: "Gebruikersstatus succesvol bijgewerkt.",
    error_user_status_update: "Fout bij bijwerken gebruikersstatus.",
    admin_search_placeholder: "Zoek op naam of e-mail...",
    loading_data: "Gegevens laden...",
    admin_streak_leaderboard: "Streak Leaderboard",
    no_streak_users: "Geen gebruikers met een actieve streak.",
    admin_select_feedback: "Selecteer een feedbackbericht om details te bekijken en te beantwoorden.",
    admin_appearance_settings: "Weergave",
    admin_security_settings: "Beveiliging",
    admin_pin_toggle_label: "Admin PIN bij inloggen inschakelen",
    admin_pin_verify_title: "Beveiligingsverificatie",
    admin_pin_verify_desc: "Om de PIN-beveiliging uit te schakelen, beantwoord de beveiligingsvraag.",
    admin_pin_secret_question: "Wat is de favoriete film van de maker?",
    admin_pin_answer_placeholder: "Jouw antwoord",
    admin_pin_error_incorrect: "Incorrect antwoord. Probeer het opnieuw.",

    // Feedback System
    feedback_title: "Feedback & Support",
    feedback_subtitle: "Heb je een vraag, een suggestie of een probleem? Laat het ons weten!",
    feedback_subject_placeholder: "Onderwerp (bv. Probleem met agenda)",
    feedback_message_placeholder: "Jouw bericht...",
    send_feedback_button: "Verstuur Feedback",
    feedback_sent_success: "Je feedback is succesvol verzonden! We nemen zo snel mogelijk contact op.",
    error_feedback_failed: "Versturen van feedback mislukt. Probeer het opnieuw.",
    your_feedback_history: "Jouw Feedbackgeschiedenis",
    no_feedback_history: "Je hebt nog geen feedback verstuurd.",
    admin_feedback_dashboard: "Feedback Inbox",
    from: "Van",
    subject: "Onderwerp",
    submitted_on: "Ingediend op",
    view_feedback: "Bekijk",
    reply_to_feedback: "Beantwoord Feedback",
    your_reply_placeholder: "Typ je antwoord hier...",
    send_reply_button: "Verstuur Antwoord",
    reply_sent_success: "Antwoord succesvol verzonden.",
    error_reply_failed: "Versturen van antwoord mislukt.",
    status_new: "Nieuw",
    status_replied: "Beantwoord",
    feedback_reply_notification_title: "Antwoord op je feedback",
    feedback_reply_notification_text: "De beheerder heeft gereageerd op je feedback over '{subject}'.",
    you: "Jij",
    admin: "Admin"
  },
  en: {
    // Auth & General
    welcome_message: "Welcome, {name}!",
    welcome_title: "Welcome to Schoolmaps!",
    welcome_description: "All your school matters in one place. Organize your files, manage your calendar, and speed up your learning process.",
    create_account_login_button: "Create Account / Login",
    register_title: "Register an Account",
    login_title: "Login",
    your_name: "Full name",
    email_address: "Email address",
    password: "Password",
    placeholder_name: "e.g., John Doe",
    placeholder_email: "your@email.com",
    placeholder_password: "********",
    school_name: "Name of your school",
    class_name: "Class (e.g., 10B)",
    education_level: "Education Level",
    register_account: "Register Account",
    login_button: "Login",
    already_account: "Already have an account? Login here",
    no_account_register: "No account yet? Register here",
    success_registration: "Registration successful! Please check your email to verify your account.",
    success_login: "Successfully logged in! Welcome back.",
    success_logout: "You have been logged out. See you next time!",
    confirm_logout: "Are you sure you want to log out?",
    forgot_password: "Forgot password?",
    password_reset_sent: "A password reset email has been sent to {email}. Your data remains safe.",
    guest_fallback_name: "User",
    default: "Default",

    // Email Verification
    verify_email_title: "Verify Your Email Address",
    verify_email_instructions: "We've sent a verification link to {email}. Please click the link to activate your account.",
    verify_email_spam_check: "Didn't receive it? Check your spam folder or request a new email below.",
    verify_email_continue_button: "I have verified, continue",
    verify_email_resend_button: "Resend",
    sending: "Sending...",
    email_sent: "Email sent!",
    skip_verification_button: "Skip verification (Test)",
    skip_verification_tooltip_title: "Temporary Test Button",
    skip_verification_tooltip_text: "The email verification is currently being revised. Use this button to temporarily proceed without verification. This option will be removed soon.",

    // Errors
    error_fill_all_fields: "Please fill in all required fields.",
    error_fill_current_step: "Please fill in all fields in this step.",
    error_select_subjects_register: "Please select at least one subject to continue.",
    error_unknown: "An unknown error occurred. Please try again.",
    error_invalid_email: "This is not a valid email address. Please check and try again.",
    error_invalid_credentials: "The email and password combination is incorrect.",
    error_email_in_use: "This email address is already in use. Please try to log in.",
    error_weak_password: "Your password is too weak. Please use at least 6 characters.",
    error_enter_email_for_reset: "Please enter your email address to reset your password.",
    error_save_settings_failed: "Failed to save settings. Please try again.",
    error_profile_pic_upload_failed: "Failed to upload profile picture. Please try again.",
    error_password_reset_failed: "Failed to send password reset email.",
    error_guest_action_not_allowed: "Guest users cannot perform this action.",
    error_profile_load_failed: "Could not load your profile. Please check your connection or try again later.",
    error_failed_to_load_tasks: "Could not load tasks. Please check your connection.",
    error_failed_to_load_sets: "Could not load study sets. Please check your connection.",
    error_failed_to_load_cards: "Could not load cards. Please check your connection.",
    error_account_disabled: "Your account has been disabled by an administrator.",
    error_reauth_failed: "Incorrect password. Please try again.",
    error_account_deletion_failed: "Failed to delete account. Please try again later.",
    error_account_cleanup_failed: "Failed to clean up account. Please try again later.",
    error_admin_login_failed: "Admin login failed. Could not load settings.",
    error_failed_to_save_admin_settings: "Failed to save admin settings.",
    error_select_file_to_upload: "Please select a file to upload.",
    error_add_file_failed: "Failed to add file: {message}",
    error_delete_file_failed: "Failed to delete files: {message}",
    error_invalid_date_time: "Invalid date or time.",
    error_save_event_failed: "Failed to save event: {message}",
    error_delete_event_failed: "Failed to delete event: {message}",
    error_fetch_notes_failed: "Failed to fetch notes.",
    error_save_note_failed: "Failed to save note: {message}",
    error_delete_note_failed: "Failed to delete note.",
    error_flashcard_set_min_cards: "You need at least 2 cards in a set for Multiple Choice mode.",
    error_general_srs_reset: "Failed to reset progress.",

    // Account Deletion
    delete_account_section_title: "Delete Account",
    delete_account_section_description: "This action is irreversible. All your data, including files, notes, and calendar items, will be permanently deleted.",
    delete_account_button: "Delete My Account",
    reauth_modal_title: "Confirm Your Identity",
    reauth_modal_description: "Please enter your password to continue. This is a security measure.",
    confirm_delete_account_button: "Yes, Delete My Account Permanently",
    deleting_account_progress: "Deleting account... This may take a moment.",
    success_account_deleted: "Your account has been successfully deleted. We're sorry to see you go.",

    // Account Cleanup
    cleanup_account_section_title: "Clean Up Account",
    cleanup_account_section_description: "This action will delete all your content (files, notes, calendar, etc.) but will keep your account and settings. This cannot be undone.",
    cleanup_account_button: "Clean Up My Account",
    reauth_modal_title_cleanup: "Confirm Account Cleanup",
    reauth_modal_description_cleanup: "Enter your password to confirm cleaning up your account. All your content will be permanently deleted.",
    confirm_cleanup_account_button: "Yes, Clean Up My Account",
    cleanup_account_progress: "Cleaning up account...",
    success_account_cleaned: "Your account has been successfully cleaned up.",

    // Navigation
    my_subjects: "My Subjects",
    calendar: "Calendar",
    extra_tools: "Extra Tools",
    flashcards: "Flashcards",
    study_timer: "Study Timer",
    notes: "Notes",
    todo_list: "To-Do List",
    settings: "Settings",
    app_info: "App Info",
    faq: "FAQ",
    logout_button: "Logout",
    feedback_support: "Feedback & Support",

    // Home & Subjects
    my_subjects_files: "Your School Files",
    profile_incomplete_message: "Your profile is not yet complete!",
    go_to_settings_message: "Go to Settings to select your subjects.",
    select_subjects: "Select your subjects",
    add_custom_subject: "Add a custom subject",
    custom_subject_placeholder: "Name of the subject...",
    add_subject_button: "Add",
    error_subject_exists: "This subject already exists.",
    error_subject_empty: "Subject name cannot be empty.",
    no_files_found: "No files found in this subject.",
    add_file_section_title: "Add File:",
    file_title_placeholder: "Title (required)",
    file_description_placeholder: "Description (optional)",
    add_file_button: "Add File",
    select_files_button: "Select Files",
    delete_selected_button: "Delete Selected",
    share_button: "Share",
    back_to_subjects: "Back to Subjects",
    back_button: "Back",
    error_enter_file_title: "Please enter a title for the file.",
    success_file_added: "File successfully added!",
    error_select_files_delete: "Select files to delete first.",
    confirm_delete_files: "Are you sure you want to delete {count} file(s)?",
    success_files_deleted: "Selected files successfully deleted!",
    share_link_copied: "Share link for '{title}' copied!",
    error_copy_share_link: "Error copying share link.",
    added_on: "Added on",
    your_files_in: "Your files in",
    your_subjects: "Your Subjects",
    recent_files_title: "Recent Files",
    no_recent_files: "You haven't added any files yet.",
    todays_agenda_title: "Today's Agenda",
    no_events_today: "No appointments for today. Enjoy your day!",
    go_to_calendar: "View full calendar",

    // Settings
    settings_title: "Settings",
    profile_section: "Profile",
    profile_picture_upload_label: "Upload profile picture:",
    profile_picture_current: "Current profile picture:",
    profile_picture_upload_success: "Profile picture successfully updated!",
    upload_profile_picture_button: "Upload Profile Picture",
    save_profile_info_button: "Save Profile",
    success_settings_saved: "Settings successfully saved!",
    choose_theme: "Choose your theme",
    font_preference: "Choose your font",
    language_preference: "Language Preference",
    dutch: "Dutch",
    english: "English",
    password_reset_section_title: "Password Reset",
    password_reset_section_description: "Click the button to receive a password reset email at {email}.",
    send_reset_email_button: "Send Reset Email",
    settings_account_section: "Account",
    settings_appearance_section: "Appearance",
    settings_help_info_section: "Help & Info",
    settings_privacy_section: "Privacy",
    privacy_policy_content: "Your privacy is important to us. This app collects minimal personal data to provide its functionality. Files you upload are stored in your private storage and are only accessible by you, unless you explicitly share them.",
    version: "Version",
    copyright: "All rights reserved.",
    saving: "Saving...",
    confirm_remove_subjects_warning: "Are you sure you want to deselect these subjects? The associated data (files, notes, etc.) will not be deleted, but will only be visible again if you re-select the subjects.",
    app_offline_message: "You are offline. Changes will be synchronized when you are back online.",
    app_back_online_message: "Welcome back online! Your data will be synchronized.",
    home_layout_title: "Customize Home Page Layout",
    home_layout_description: "Drag and drop the widgets to rearrange the order on your home page.",
    widget_subjects: "My Subjects",
    widget_agenda: "Today's Agenda",
    widget_files: "Recent Files",
    notifications_settings_title: "Notification Settings",
    enable_notifications: "Enable notifications",

    // Calendar
    calendar_title: "Your Calendar",
    add_event: "New Event",
    event_title: "Event title",
    event_description: "Description (optional)",
    event_type: "Type",
    event_subject: "Subject",
    select_date: "Date",
    select_start_time: "Start time",
    select_end_time: "End time",
    add_event_button: "Add Event",
    no_events_day: "No events for this day.",
    edit_event: "Edit",
    delete_event_confirm: "Are you sure you want to delete '{title}'?",
    event_test: "Test",
    event_presentation: "Presentation",
    event_homework: "Homework",
    event_oral: "Oral",
    event_other: "Other",
    all_day: "All day",
    today: "Today",
    week_of: "Week of",
    previous_week: "Previous",
    next_week: "Next",
    error_enter_event_title: "Please enter a title for the event.",
    success_event_added: "Event successfully added!",
    success_event_updated: "Event successfully updated!",
    success_event_deleted: "Event successfully deleted!",
    all_subjects_option: "All Subjects",
    select_subject: "Select Subject",

    // Tools
    notes_title: "Notes",
    add_note_title_placeholder: "Note title (required)",
    add_note_content_placeholder: "Start typing...",
    add_note_button: "New Note",
    save_note_button: "Save",
    confirm_delete_note: "Are you sure you want to delete this note?",
    note_added_success: "Note successfully added!",
    note_updated_success: "Note successfully updated!",
    note_deleted_success: "Note successfully deleted!",
    error_empty_note_title: "Note title cannot be empty.",

    todo_list_title: "Your To-Do List",
    add_task_placeholder: "Add a new task...",
    add_task_button: "Add Task",
    no_tasks_found: "No tasks found. Add one!",
    task_added_success: "Task successfully added!",
    task_deleted_success: "Task successfully deleted!",
    task_updated_success: "Task successfully updated!",
    confirm_delete_task: "Are you sure you want to delete this task?",
    error_empty_task: "Task cannot be empty.",

    flashcards_title: "Your Flashcards",
    add_flashcard: "Add Flashcard",
    question: "Question",
    answer: "Answer",
    add_card_button: "Add Card",
    next_card: "Next",
    prev_card: "Previous",
    flip_card: "Flip",
    no_flashcards_found: "No flashcards found for this set.",
    all_cards_learned_title: "Good job!",
    all_cards_learned_desc: "You have learned all the cards for now. Reset the progress to start over or choose another method.",
    reset_and_start_over_button: "Reset & Learn Again",
    choose_other_method_button: "Choose Other Method",
    confirm_delete_flashcard: "Are you sure you want to delete this flashcard?",
    flashcard_added_success: "Flashcards successfully added!",
    flashcard_deleted_success: "Flashcard successfully deleted!",
    error_empty_flashcard: "Question and answer cannot be empty.",

    // New Flashcard Deck translations
    select_a_subject_first: "Select a subject to start",
    sets_for_subject: "Study sets for {subject}",
    select_set: "Select a Study Set",
    create_new_set: "Create New Set",
    set_name_placeholder: "Name of your set (e.g., Chapter 1)",
    create_set_button: "Create Set",
    no_sets_found: "No study sets found for this subject.",
    confirm_delete_set: "Are you sure you want to delete the set '{name}' and all cards in it?",
    set_added_success: "Set successfully created!",
    set_deleted_success: "Set successfully deleted!",
    error_empty_set_name: "Set name cannot be empty.",
    back_to_sets: "Back to Sets",
    back_to_subjects_selection: "Back to subjects",
    manage_cards: "Manage Cards",
    cards_in_set: "{count} cards",
    add_more_rows: "Add 5 more rows",

    // Flashcard Study Modes & Summary
    choose_study_mode: "Choose a study method",
    study_mode_learn_title: "Learn",
    study_mode_learn_desc: "Smart algorithm (SRS) to get words into your long-term memory. Ideal for true learning.",
    study_mode_cram_title: "Cram",
    study_mode_cram_desc: "Quickly go through all the cards. Perfect for a quick review right before a test.",
    study_mode_mc_title: "Multiple Choice",
    study_mode_mc_desc: "Test your knowledge with automatically generated multiple-choice questions. Challenge yourself!",
    start_session: "Start Session",
    show_answer: "Show Answer",
    feedback_again: "Again",
    feedback_good: "Good",
    reset_srs_progress: "Reset learning progress",
    reset_srs_confirm: "Are you sure you want to reset the learning progress for this set? All cards will be treated as new.",
    session_complete: "Session Complete!",
    your_score: "Your score: {correct} / {total}",
    well_done_message: "Well done! Keep it up.",
    study_again_button: "Study Again",
    cards_to_go: "{count} cards to go",
    loading_cards: "Loading cards...",

    study_timer_title: "Study Timer",
    focus_session: "Focus",
    break_session: "Break",
    focus_session_complete: "Focus session complete! Time for a break.",
    break_session_complete: "Break's over! Time to focus again.",
    focusing_on: "Focusing on:",
    loading_tasks: "Loading tasks...",
    no_specific_task: "-- No specific task --",

    // UI
    confirm_button: "Confirm",
    cancel_button: "Cancel",
    close_button: "Close",
    select_level: "Select Level",
    view_button: "View",
    delete: "Delete",
    copy_link: "Copy Link",
    next_button: "Next",
    uploading: "Uploading...",

    // Intro Tutorial
    intro_step1_title: "Everything in One Place",
    intro_step1_text: "Keep all your files, notes, and summaries organized by subject. No more searching for that one report.",
    intro_step2_title: "Manage Your Time",
    intro_step2_text: "Never miss a deadline with a clear calendar for all your tests, homework, and appointments.",
    intro_step3_title: "Study Smarter",
    intro_step3_text: "Use our smart tools like flashcards and the study timer to learn more efficiently and get better grades.",
    intro_step4_title: "Make It Your Place",
    intro_step4_text: "Choose your own colors and font to make the app perfectly match your style. Your school, your look.",
    intro_step5_title: "Ready to Get Started?",
    intro_step5_text: "Transform your school life. Create an account or log in to get started right away.",
    intro_finish_button: "Let's Go!",

    // Notifications & Streak
    notifications: "Notifications",
    notifications_title: "Notifications",
    no_notifications: "You don't have any notifications yet.",
    no_notifications_disabled_title: "Notifications are disabled",
    no_notifications_disabled_text: "You can enable them in Settings.",
    mark_all_as_read: "Mark all as read",
    clear_all_notifications: "Clear all notifications",
    confirm_clear_all_notifications: "Are you sure you want to delete all notifications? This cannot be undone.",
    notifications_cleared: "All notifications have been cleared.",
    streak_notification: "Great job! You've reached a streak of {count} days. Keep it up!",
    streak_lost_notification_title: "Streak Lost",
    streak_lost_notification_text: "Oh no! Your streak of {count} days has been broken. Start a new one today!",
    streak_days: "{count} days",

    // Admin
    admin_dashboard: "Admin Dashboard",
    users: "Users",
    broadcasts: "Broadcasts",
    send_broadcast: "Send Broadcast",
    broadcast_title_placeholder: "Title of your broadcast",
    broadcast_message_placeholder: "Type your message here...",
    send_message_button: "Send Message",
    broadcast_success: "Broadcast sent successfully!",
    error_broadcast_failed: "Failed to send broadcast.",
    error_broadcast_empty: "Broadcast title and message cannot be empty.",
    error_deletion_failed: "Deletion failed.",
    past_broadcasts: "Past Broadcasts",
    no_past_broadcasts: "No broadcasts have been sent yet.",
    delete_all_broadcasts: "Delete All Broadcasts",
    confirm_delete_all_broadcasts: "Are you sure you want to delete all broadcasts? This cannot be undone.",
    confirm_delete_all_broadcasts_and_notifications: "Are you sure you want to delete all broadcasts and their associated notifications from all users? This cannot be undone.",
    all_broadcasts_deleted: "All broadcasts and notifications have been deleted.",
    refresh_data: "Refresh Data",
    actions: "Actions",
    status: "Status",
    active: "Active",
    disabled: "Disabled",
    last_login: "Last Login",
    enable_user: "Enable",
    disable_user: "Disable",
    confirm_disable_user: "Are you sure you want to disable user {name}? They will not be able to log in.",
    confirm_enable_user: "Are you sure you want to enable user {name}? They will be able to log in again.",
    user_status_updated: "User status successfully updated.",
    error_user_status_update: "Error updating user status.",
    admin_search_placeholder: "Search by name or email...",
    loading_data: "Loading data...",
    admin_streak_leaderboard: "Streak Leaderboard",
    no_streak_users: "No users with an active streak.",
    admin_select_feedback: "Select a feedback message to view details and reply.",
    admin_appearance_settings: "Appearance",
    admin_security_settings: "Security",
    admin_pin_toggle_label: "Enable Admin PIN on Login",
    admin_pin_verify_title: "Security Verification",
    admin_pin_verify_desc: "To disable PIN protection, please answer the security question.",
    admin_pin_secret_question: "What is the creator's favorite movie?",
    admin_pin_answer_placeholder: "Your answer",
    admin_pin_error_incorrect: "Incorrect answer. Please try again.",

    // Feedback System
    feedback_title: "Feedback & Support",
    feedback_subtitle: "Have a question, a suggestion, or a problem? Let us know!",
    feedback_subject_placeholder: "Subject (e.g., Problem with calendar)",
    feedback_message_placeholder: "Your message...",
    send_feedback_button: "Send Feedback",
    feedback_sent_success: "Your feedback has been sent successfully! We will get back to you as soon as possible.",
    error_feedback_failed: "Failed to send feedback. Please try again.",
    your_feedback_history: "Your Feedback History",
    no_feedback_history: "You haven't sent any feedback yet.",
    admin_feedback_dashboard: "Feedback Inbox",
    from: "From",
    subject: "Subject",
    submitted_on: "Submitted on",
    view_feedback: "View",
    reply_to_feedback: "Reply to Feedback",
    your_reply_placeholder: "Type your reply here...",
    send_reply_button: "Send Reply",
    reply_sent_success: "Reply sent successfully.",
    error_reply_failed: "Failed to send reply.",
    status_new: "New",
    status_replied: "Replied",
    feedback_reply_notification_title: "Reply to your feedback",
    feedback_reply_notification_text: "The administrator has replied to your feedback about '{subject}'.",
    you: "You",
    admin: "Admin",
  }
};